### ISSUE TITLE
How should I get the author of a quote?

### ISSUE THREAD

**Issue by ghost** [yinghang/Chrome-Momentum-Extension#1]
Hi, through the momentum-quote.js, just only get the words of a quote, but don't know it's whose quote.

Is there any other function to get it ?

**Comment by yinghang** [comment]
Yeah sorry, it's just from an API that I wrote myself and I didn't think to include the author of the quote. You can perhaps find some other APIs that can give you that.

EDIT: Check this out - [http://quotes.rest](http://quotes.rest)
