### ISSUE TITLE
How to change clock to 24 hour version?

### ISSUE THREAD

**Issue by thedael** [yinghang/Chrome-Momentum-Extension#2]

**Comment by yinghang** [comment]
Take out these 3 lines of code and you should be good.

https://github.com/yinghang/chrome-momentum/blob/master/js/momentum.js#L49-L51

**Comment by yinghang** [comment]
However, this repo is slightly out of date, and I've re-created a newer version that's built using React [here](https://github.com/yinghang/project-mi-casa). Feel free to take a look!
